#include <furi.h>
#include <dialogs/dialogs.h>

/* generated by fbt from .png files in images folder */
#include <hello_flipper_icons.h>

int32_t hello_flipper_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("HelloFlipper", "Hello world");

    DialogsApp* dialogs = furi_record_open(RECORD_DIALOGS);
    DialogMessage* message = dialog_message_alloc();

    dialog_message_set_header(message, "Hello world", 64, 20, AlignCenter, AlignTop);
    dialog_message_set_text(message, "I'm hello_flipper!", 64, 32, AlignCenter, AlignTop);
    dialog_message_show(dialogs, message);

    dialog_message_free(message);
    furi_record_close(RECORD_DIALOGS);

    return 0;
}
